### ISSUE TITLE
Embedded Youtube Video anzeigen

### ISSUE THREAD

**Issue by ItsReallyMeDE** [JonesfromHan/Website-progress#13]

**Comment by JonesfromHan** [comment]
Kannst dir mal den Code von der DVD Website anschauen

**Comment by ItsReallyMeDE** [comment]
Stimmt. - Würde gerne noch ne Verquickung in der Form machen, dass man Videos auch in der Gallery haben kann. Weiss aber selber noch nicht genau wie ich mir das vorstelle :-)

**Comment by ItsReallyMeDE** [comment]
Ich schliesse das mal wegen zu unkonkret :-)
