### ISSUE TITLE
Alte Dropbox Gallerien hier verlinken

### ISSUE THREAD

**Issue by ItsReallyMeDE** [JonesfromHan/Website-progress#14]
man könnte sie auch importieren. Mal sehen was schneller geht...

**Comment by JonesfromHan** [comment]
Fände importieren schöner

**Comment by ItsReallyMeDE** [comment]
Ja

**Comment by ItsReallyMeDE** [comment]
Alles wird im Laufe der Zeit portiert - oder dem Vergessen überantwortet
