### ISSUE TITLE
Kalender mit Inhalt füllen

### ISSUE THREAD

**Issue by JonesfromHan** [JonesfromHan/Website-progress#17]

**Comment by ItsReallyMeDE** [comment]
Mach ich. Dann hätt ich aber gerne vorher entweder die Syntax-Doku oder einen Beispieleintrag für den Kaffeeklatsch. Das reicht auch.

**Comment by ItsReallyMeDE** [comment]
Sorry, gerade gesehen, dass es Einträge in der dev Instanz gibt.
Kann man schon Bilder einblenden?
Gibt anscheinend noch keine Defaultbilder für die Bands, richtig?

**Comment by ItsReallyMeDE** [comment]
Erstmal okay so...
