### ISSUE TITLE
Kalenderprobleme

### ISSUE THREAD

**Issue by ItsReallyMeDE** [JonesfromHan/Website-progress#23]
Beschreibungstext: Im Kalendereintrag verwendete tags < br > < b > < i > werden geparst. Das ist gut. 
< a href > leider nicht. Das wär aber auch sinnvoll um auf externe Infos zum Event zu verlinken (Stadtfeste etc)

Bild:
Wenn picture=xyz fehlt, dann wird das Defaultbild gezeigt. Wenn man "picture=def" eingibt wird gar kein Bild gezeigt.
Ich habe in Deinem Calendersnippet für mu und bmb neue Bilder statt default.jpg eingetragen (mu.jpg und bmb.jpg). Trotzdem wird ohne picture tag nur das graue Bild gezeigt. Eingabe von picture=mu.jpg funzt jedoch.

Band-Bild: Da ist momentan immer ein Hyperlink drauf, der zeigt aber ins Nirvana. Wenn ich ref=http://www.google.de eingebe, dann funzt das nicht.

**Comment by JonesfromHan** [comment]
#22

**Comment by JonesfromHan** [comment]
- [x] ~~Hyperlinks fixen~~ wontfix
- [x] Markdownsupport hinzufügen
- [x] "picture=def" fixen
- [x] Standartbilder fixen (schon mal den Cache geleert?)
- [x] Link auf Bild fixen

**Comment by JonesfromHan** [comment]
Dass Hyperlinks nicht funzen liegt daran, dass sinnvollerweise Anführungszeichen maskiert werden. Würde das SEHR ungerne ändern!

**Comment by ItsReallyMeDE** [comment]
- [x]  ~~Bitte Anzeige von Anfangs- UND Enduhrzeit (falls vorhanden)~~

**Comment by ItsReallyMeDE** [comment]
- [x] ~~Bei ganztägigen Events bitte Uhrzeit weglassen!~~
- [x] Weil sich Leute die Seite bookmarken werden: Seitentitel "BMB Kalender", "MU Kalender"
(Könnte man über [[*longtitle]] realisieren, der ja auf der Seite bisher nicht verwendet wird
        <title>[[*longtitle]] - [[++site_name]]</title> )

**Comment by JonesfromHan** [comment]
> Ich habe in Deinem Calendersnippet für mu und bmb neue Bilder statt default.jpg eingetragen (mu.jpg und bmb.jpg). Trotzdem wird ohne picture tag nur das graue Bild gezeigt. Eingabe von picture=mu.jpg funzt jedoch.

Ja, hast du. An der falschen Stelle :joy:

**Comment by JonesfromHan** [comment]
> Bitte Anzeige von Anfangs- UND Enduhrzeit (falls vorhanden)
> Bei ganztägigen Events bitte Uhrzeit weglassen!

Theoretisch möglich, praktisch muss ich den Teil neu schreiben. Verschoben in #24

**Comment by JonesfromHan** [comment]
Mach hier zu, bitte neue Issues öffnen!
