### ISSUE TITLE
Kalender in Hauptinstanz kopieren

### ISSUE THREAD

**Issue by JonesfromHan** [JonesfromHan/Website-progress#26]
- [x] #22 
- [x] #24 
- [x] #17

**Comment by ItsReallyMeDE** [comment]
Aber erst kopieren, wenn die Testdaten gelöscht sind. Kann ich machen. Trage dann auch gleich die bekannten richtigen Daten ein

**Comment by ItsReallyMeDE** [comment]
Ach so: Gehe davon aus, dass nur Snippet, Chunk & Bandbilder kopiert werden müssen. Alles andere bleibt wie es ist, richtig?

**Comment by JonesfromHan** [comment]
Hab mal #17 referenziert

**Comment by ItsReallyMeDE** [comment]
:-)

**Comment by JonesfromHan** [comment]
In den Ressourcen muss auch was verändert werden

**Comment by JonesfromHan** [comment]
Alle Aufgaben erfüllt. Wer macht das?
