### ISSUE TITLE
Alternative Kalenderdarstellung als (druckbare) Liste

### ISSUE THREAD

**Issue by ItsReallyMeDE** [JonesfromHan/Website-progress#27]
Zum Einen, weil René das schon die ganze Zeit haben will, zum anderen weil die aktuelle Darstellung mehr Show ist - und recht unpraktisch, wenn man sich schnell Überblick über die Termine verschaffen will

**Comment by ItsReallyMeDE** [comment]
Die druckbare Darstellung sollte folgendes ermöglichen

- [ ] Ausdruck der internen (!) Kalender (Der Websitekalender ist hier nicht gefragt)
- [ ] Chronologischer Ausdruck der Termine aller Band- plus Vereins(MVW)kalender
- [ ] Dito nur für eine Band. Also z.B. MU+MVW

**Comment by JonesfromHan** [comment]
Ist das noch relevant?

**Comment by ItsReallyMeDE** [comment]
Wenn du René fragst, sagt er bestimmt "Ja". ;-)
Wenn es seine Papierterminlisten ersetzen soll, dann muss es ja ne präzise Semantik geben
-Datum
-Startzeit
-Dauer
-Ort
-Textfeld
-Setliste
...
Wenn das mal kommt, dann wohl eher aus CanU heraus, oder?

**Comment by JonesfromHan** [comment]
Gehört zum CanU
