### ISSUE TITLE
Es gibt jetzt Ergänzungen, die nur in www leben, aber nicht in dev

### ISSUE THREAD

**Issue by ItsReallyMeDE** [JonesfromHan/Website-progress#33]
Konsequenz: wenn man was in dev testet, muss man genau hinschauen, dass man beim Portieren keinen veralteten Inhalt und/oder Code nach www kopiert :-)

**Comment by JonesfromHan** [comment]
Gut zu wissen...

**Comment by ItsReallyMeDE** [comment]
Potentielle "Gefahrenstellen"
- main.css (meine Änderungen sind entweder am Ende oder mit \*CH\* gekennzeichnet)
- zur Ressource gehöriges Template
- Templatevariablen
- identisch benannte Chunks, die aber evtl unterschiedlichen Inhalt haben
- Eigenschaftengruppen (ressource groups) von snippets
etc

**Comment by JonesfromHan** [comment]
Noch relevant/der Fall?
