### ISSUE TITLE
Monatliche mailman-Meldungen über Listen-Abos unterdrücken

### ISSUE THREAD

**Issue by ItsReallyMeDE** [JonesfromHan/Website-progress#9]
Sonst steigen uns die Leute aufs Dach, fürchte ich ...

**Comment by JonesfromHan** [comment]
Hab ich das nicht gemacht gehabt?

**Comment by JonesfromHan** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/8125717/23225625/c82605ca-f932-11e6-8b3a-f7bb2d973ebd.PNG)
Meinst du das hier?
